Traceback (most recent call last):
  File "train_net.py", line 435, in <module>
    launch(
  File "/opt/miniconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/launch.py", line 84, in launch
    main_func(*args)
  File "train_net.py", line 423, in main
    trainer = Trainer(cfg)
  File "/opt/miniconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 376, in __init__
    model = self.build_model(cfg)
  File "/opt/miniconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/engine/defaults.py", line 514, in build_model
    model = build_model(cfg)
  File "/opt/miniconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/opt/miniconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/config/config.py", line 190, in wrapped
    init_func(self, **explicit_args)
  File "/OneFormer/oneformer/oneformer_model.py", line 117, in __init__
    self.thing_indices = [k for k in self.metadata.thing_dataset_id_to_contiguous_id.keys()]
  File "/opt/miniconda3/envs/oneformer/lib/python3.8/site-packages/detectron2/data/catalog.py", line 131, in __getattr__
    raise AttributeError(
AttributeError: Attribute 'thing_dataset_id_to_contiguous_id' does not exist in the metadata of dataset '/mnt/source/datasets/mapillary_vistas/training/v2.0/panoptic': metadata is empty.